- name: Druid Imply Distribution Uninstall
  hosts: tag_vmgroup_druidmaster,tag_vmgroup_druidquery,tag_vmgroup_druiddata
  become: yes
  tasks:
  - name: Stop Druid services
    systemd:
      name: "{{ item }}"
      state: stopped
    with_items:
      - masterwithzk
      - masternozk
      - data
      - query
    ignore_errors: True

  - name: Uninstall druid
    file:
      path: "{{ item }}"
      state: absent
    with_items:
      - /etc/systemd/system/masterwithzk.service
      - /etc/systemd/system/masternozk.service
      - /etc/systemd/system/data.service
      - /etc/systemd/system/query.service
      - /opt/imply
      - /var/ssl/private
